{% set version = "1.2.1" %}

package:
  name: sofia_redux
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/sofia-redux/sofia_redux-{{ version }}.tar.gz
  sha256: 111f80c92b6fa827cc25763d82e32e23c7472a5d3a377f4a3b452d8164dc2494

build:
  noarch: python
  entry_points:
    - redux_pipe=sofia_redux.pipeline.sofia.sofia_pipe:main
    - redux=sofia_redux.pipeline.sofia.sofia_app:main
    - qad=sofia_redux.pipeline.gui.qad.qad_app:main
    - pipecal_applyphot=sofia_redux.calibration.pipecal_applyphot:main
    - hawc_calibration=sofia_redux.calibration.standard_model.hawc_calibration:main
    - eospec=sofia_redux.visualization.controller:main
  script: {{ PYTHON }} -m pip install . --no-deps

requirements:
  build:
    - pip
    - python
    - setuptools
    - setuptools_scm
  host:
    - pip
    - python>=3.8
  run:
    - python>=3.8
    - astropy>=4.0
    - astroquery>=0.4.4
    - bottleneck>=1.3.1
    - cloudpickle>=1.6.0
    - configobj>=5
    - cycler>=0.10.0
    - dill>=0.3
    - joblib>=0.14.1
    - matplotlib>=3.3
    - more-itertools>=8.5.0
    - numba>=0.53.1
    - numpy>=1.20.0
    - pandas>=1.3
    - photutils>=0.7.2
    - psutil>=5.8.0
    - regex>=2021.4.4
    - pyqt>=5.9.2
    - scikit-image<0.19
    - scikit-learn>0.22.1
    - scipy>=1.4.1

test:
  imports:
    - sofia_redux
  commands:
    - redux_pipe --help
    - redux --help
    - qad --help

about:
  home: https://sofia-usra.github.io/sofia_redux/
  dev_url: https://github.com/SOFIA-USRA/sofia_redux
  license: BSD-3-Clause
  summary: 'SOFIA data reduction pipelines'
  description: |
    SOFIA Redux (sofia_redux) contains data processing pipelines and
    algorithms for instruments on the Stratospheric Observatory for
    Infrared Astronomy (SOFIA).
