# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qad_plot_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotSettingsDialog(object):
    def setupUi(self, PlotSettingsDialog):
        PlotSettingsDialog.setObjectName("PlotSettingsDialog")
        PlotSettingsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PlotSettingsDialog.resize(489, 411)
        PlotSettingsDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(PlotSettingsDialog)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(PlotSettingsDialog)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(PlotSettingsDialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.shareAxesBox = QtWidgets.QComboBox(PlotSettingsDialog)
        self.shareAxesBox.setObjectName("shareAxesBox")
        self.shareAxesBox.addItem("")
        self.shareAxesBox.addItem("")
        self.shareAxesBox.addItem("")
        self.shareAxesBox.addItem("")
        self.gridLayout.addWidget(self.shareAxesBox, 3, 1, 1, 1)
        self.colorBox = QtWidgets.QLineEdit(PlotSettingsDialog)
        self.colorBox.setObjectName("colorBox")
        self.gridLayout.addWidget(self.colorBox, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(PlotSettingsDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.histBinBox = QtWidgets.QLineEdit(PlotSettingsDialog)
        self.histBinBox.setObjectName("histBinBox")
        self.gridLayout.addWidget(self.histBinBox, 7, 1, 1, 1)
        self.windowSizeBox = QtWidgets.QLineEdit(PlotSettingsDialog)
        self.windowSizeBox.setObjectName("windowSizeBox")
        self.gridLayout.addWidget(self.windowSizeBox, 1, 1, 1, 1)
        self.p2pReferenceBox = QtWidgets.QLineEdit(PlotSettingsDialog)
        self.p2pReferenceBox.setObjectName("p2pReferenceBox")
        self.gridLayout.addWidget(self.p2pReferenceBox, 12, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(PlotSettingsDialog)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 12, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(PlotSettingsDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.histLimitsBox = QtWidgets.QLineEdit(PlotSettingsDialog)
        self.histLimitsBox.setObjectName("histLimitsBox")
        self.gridLayout.addWidget(self.histLimitsBox, 8, 1, 1, 1)
        self.windowUnitsBox = QtWidgets.QComboBox(PlotSettingsDialog)
        self.windowUnitsBox.setObjectName("windowUnitsBox")
        self.windowUnitsBox.addItem("")
        self.windowUnitsBox.addItem("")
        self.gridLayout.addWidget(self.windowUnitsBox, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(PlotSettingsDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.separatePlotsBox = QtWidgets.QCheckBox(PlotSettingsDialog)
        self.separatePlotsBox.setText("")
        self.separatePlotsBox.setObjectName("separatePlotsBox")
        self.gridLayout.addWidget(self.separatePlotsBox, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(PlotSettingsDialog)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(PlotSettingsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(PlotSettingsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(PlotSettingsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.summaryStatBox = QtWidgets.QComboBox(PlotSettingsDialog)
        self.summaryStatBox.setObjectName("summaryStatBox")
        self.summaryStatBox.addItem("")
        self.summaryStatBox.addItem("")
        self.summaryStatBox.addItem("")
        self.summaryStatBox.addItem("")
        self.gridLayout.addWidget(self.summaryStatBox, 9, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(PlotSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PlotSettingsDialog)
        self.buttonBox.accepted.connect(PlotSettingsDialog.accept)
        self.buttonBox.rejected.connect(PlotSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PlotSettingsDialog)
        PlotSettingsDialog.setTabOrder(self.windowSizeBox, self.histBinBox)
        PlotSettingsDialog.setTabOrder(self.histBinBox, self.histLimitsBox)
        PlotSettingsDialog.setTabOrder(self.histLimitsBox, self.p2pReferenceBox)

    def retranslateUi(self, PlotSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        PlotSettingsDialog.setWindowTitle(_translate("PlotSettingsDialog", "Plot Settings"))
        self.label_7.setText(_translate("PlotSettingsDialog", "Plot color cycle"))
        self.label_5.setText(_translate("PlotSettingsDialog", "Histogram range"))
        self.label.setText(_translate("PlotSettingsDialog", "Share axes"))
        self.shareAxesBox.setToolTip(_translate("PlotSettingsDialog", "Specify axes to share, between separate plots."))
        self.shareAxesBox.setItemText(0, _translate("PlotSettingsDialog", "none"))
        self.shareAxesBox.setItemText(1, _translate("PlotSettingsDialog", "x"))
        self.shareAxesBox.setItemText(2, _translate("PlotSettingsDialog", "y"))
        self.shareAxesBox.setItemText(3, _translate("PlotSettingsDialog", "both"))
        self.colorBox.setToolTip(_translate("PlotSettingsDialog", "Set to any valid matplotlib colormap name."))
        self.label_4.setText(_translate("PlotSettingsDialog", "Histogram binning"))
        self.histBinBox.setToolTip(_translate("PlotSettingsDialog", "Binning strategy for histograms."))
        self.windowSizeBox.setToolTip(_translate("PlotSettingsDialog", "Analysis window around cursor."))
        self.p2pReferenceBox.setToolTip(_translate("PlotSettingsDialog", "Reference frame number for pixel-to-pixel comparisons."))
        self.label_6.setText(_translate("PlotSettingsDialog", "P2P reference"))
        self.label_2.setText(_translate("PlotSettingsDialog", "Analysis window size"))
        self.histLimitsBox.setToolTip(_translate("PlotSettingsDialog", "Set range as min,max if desired."))
        self.windowUnitsBox.setToolTip(_translate("PlotSettingsDialog", "Units for window size."))
        self.windowUnitsBox.setItemText(0, _translate("PlotSettingsDialog", "pixels"))
        self.windowUnitsBox.setItemText(1, _translate("PlotSettingsDialog", "arcsec"))
        self.label_3.setText(_translate("PlotSettingsDialog", "Separate plots"))
        self.separatePlotsBox.setToolTip(_translate("PlotSettingsDialog", "If not set, new plots will be added to existing axes."))
        self.label_8.setText(_translate("PlotSettingsDialog", "Summary statistic"))
        self.label_9.setText(_translate("PlotSettingsDialog", "Histogram (\'s\'):"))
        self.label_10.setText(_translate("PlotSettingsDialog", "General:"))
        self.label_11.setText(_translate("PlotSettingsDialog", "Pixel-to-pixel (\'p\'):"))
        self.summaryStatBox.setItemText(0, _translate("PlotSettingsDialog", "mean"))
        self.summaryStatBox.setItemText(1, _translate("PlotSettingsDialog", "median"))
        self.summaryStatBox.setItemText(2, _translate("PlotSettingsDialog", "clipped mean"))
        self.summaryStatBox.setItemText(3, _translate("PlotSettingsDialog", "clipped median"))

