# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qad_phot_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PhotometryDialog(object):
    def setupUi(self, PhotometryDialog):
        PhotometryDialog.setObjectName("PhotometryDialog")
        PhotometryDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PhotometryDialog.resize(488, 292)
        PhotometryDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(PhotometryDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.radialPlotBox = QtWidgets.QCheckBox(PhotometryDialog)
        self.radialPlotBox.setText("")
        self.radialPlotBox.setObjectName("radialPlotBox")
        self.gridLayout.addWidget(self.radialPlotBox, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(PhotometryDialog)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(PhotometryDialog)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.bgrinBox = QtWidgets.QLineEdit(PhotometryDialog)
        self.bgrinBox.setObjectName("bgrinBox")
        self.gridLayout.addWidget(self.bgrinBox, 5, 1, 1, 1)
        self.bgwidBox = QtWidgets.QLineEdit(PhotometryDialog)
        self.bgwidBox.setObjectName("bgwidBox")
        self.gridLayout.addWidget(self.bgwidBox, 6, 1, 1, 1)
        self.fwhmUnitsBox = QtWidgets.QComboBox(PhotometryDialog)
        self.fwhmUnitsBox.setObjectName("fwhmUnitsBox")
        self.fwhmUnitsBox.addItem("")
        self.fwhmUnitsBox.addItem("")
        self.gridLayout.addWidget(self.fwhmUnitsBox, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(PhotometryDialog)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.fwhmBox = QtWidgets.QLineEdit(PhotometryDialog)
        self.fwhmBox.setObjectName("fwhmBox")
        self.gridLayout.addWidget(self.fwhmBox, 3, 1, 1, 1)
        self.modelTypeBox = QtWidgets.QComboBox(PhotometryDialog)
        self.modelTypeBox.setObjectName("modelTypeBox")
        self.modelTypeBox.addItem("")
        self.modelTypeBox.addItem("")
        self.gridLayout.addWidget(self.modelTypeBox, 1, 1, 1, 1)
        self.windowSizeBox = QtWidgets.QLineEdit(PhotometryDialog)
        self.windowSizeBox.setObjectName("windowSizeBox")
        self.gridLayout.addWidget(self.windowSizeBox, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(PhotometryDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(PhotometryDialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(PhotometryDialog)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(PhotometryDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.apradUnitsBox = QtWidgets.QComboBox(PhotometryDialog)
        self.apradUnitsBox.setObjectName("apradUnitsBox")
        self.apradUnitsBox.addItem("")
        self.apradUnitsBox.addItem("")
        self.gridLayout.addWidget(self.apradUnitsBox, 4, 2, 1, 1)
        self.apradBox = QtWidgets.QLineEdit(PhotometryDialog)
        self.apradBox.setObjectName("apradBox")
        self.gridLayout.addWidget(self.apradBox, 4, 1, 1, 1)
        self.windowUnitsBox = QtWidgets.QComboBox(PhotometryDialog)
        self.windowUnitsBox.setObjectName("windowUnitsBox")
        self.windowUnitsBox.addItem("")
        self.windowUnitsBox.addItem("")
        self.gridLayout.addWidget(self.windowUnitsBox, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(PhotometryDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PhotometryDialog)
        self.buttonBox.accepted.connect(PhotometryDialog.accept)
        self.buttonBox.rejected.connect(PhotometryDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PhotometryDialog)
        PhotometryDialog.setTabOrder(self.radialPlotBox, self.modelTypeBox)
        PhotometryDialog.setTabOrder(self.modelTypeBox, self.windowSizeBox)
        PhotometryDialog.setTabOrder(self.windowSizeBox, self.fwhmBox)
        PhotometryDialog.setTabOrder(self.fwhmBox, self.fwhmUnitsBox)
        PhotometryDialog.setTabOrder(self.fwhmUnitsBox, self.apradBox)
        PhotometryDialog.setTabOrder(self.apradBox, self.apradUnitsBox)
        PhotometryDialog.setTabOrder(self.apradUnitsBox, self.bgrinBox)
        PhotometryDialog.setTabOrder(self.bgrinBox, self.bgwidBox)

    def retranslateUi(self, PhotometryDialog):
        _translate = QtCore.QCoreApplication.translate
        PhotometryDialog.setWindowTitle(_translate("PhotometryDialog", "Photometry Settings"))
        self.radialPlotBox.setToolTip(_translate("PhotometryDialog", "Display radial profiles for fit sources."))
        self.label_7.setText(_translate("PhotometryDialog", "Background width"))
        self.label_9.setText(_translate("PhotometryDialog", "Show radial plots"))
        self.bgrinBox.setToolTip(_translate("PhotometryDialog", "Starting radius of background annulus. Set to \'none\' to ignore background."))
        self.bgwidBox.setToolTip(_translate("PhotometryDialog", "Width of background annulus."))
        self.fwhmUnitsBox.setToolTip(_translate("PhotometryDialog", "FWHM units."))
        self.fwhmUnitsBox.setItemText(0, _translate("PhotometryDialog", "arcsec"))
        self.fwhmUnitsBox.setItemText(1, _translate("PhotometryDialog", "pixels"))
        self.label_5.setText(_translate("PhotometryDialog", "Aperture radius"))
        self.fwhmBox.setToolTip(_translate("PhotometryDialog", "Expected source width, as FWHM."))
        self.modelTypeBox.setToolTip(_translate("PhotometryDialog", "Profile type to fit."))
        self.modelTypeBox.setItemText(0, _translate("PhotometryDialog", "Moffat"))
        self.modelTypeBox.setItemText(1, _translate("PhotometryDialog", "Gaussian"))
        self.windowSizeBox.setToolTip(_translate("PhotometryDialog", "Region to consider for fitting."))
        self.label_4.setText(_translate("PhotometryDialog", "Starting FWHM"))
        self.label.setText(_translate("PhotometryDialog", "Model type"))
        self.label_6.setText(_translate("PhotometryDialog", "Background inner radius"))
        self.label_2.setText(_translate("PhotometryDialog", "Window size"))
        self.apradUnitsBox.setToolTip(_translate("PhotometryDialog", "Aperture radius and width units."))
        self.apradUnitsBox.setItemText(0, _translate("PhotometryDialog", "arcsec"))
        self.apradUnitsBox.setItemText(1, _translate("PhotometryDialog", "pixels"))
        self.apradBox.setToolTip(_translate("PhotometryDialog", "Radius of circular aperture, for summing flux."))
        self.windowUnitsBox.setToolTip(_translate("PhotometryDialog", "Units for window size."))
        self.windowUnitsBox.setItemText(0, _translate("PhotometryDialog", "pixels"))
        self.windowUnitsBox.setItemText(1, _translate("PhotometryDialog", "arcsec"))

