# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple_spec_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(919, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(7)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.control_frame = QtWidgets.QGroupBox(self.splitter)
        self.control_frame.setMinimumSize(QtCore.QSize(330, 0))
        self.control_frame.setObjectName("control_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.control_frame)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 404, 1359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.file_panel_frame = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.file_panel_frame.setObjectName("file_panel_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.file_panel_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.collapse_file_choice_button = QtWidgets.QToolButton(self.file_panel_frame)
        self.collapse_file_choice_button.setMinimumSize(QtCore.QSize(12, 12))
        self.collapse_file_choice_button.setMaximumSize(QtCore.QSize(12, 12))
        self.collapse_file_choice_button.setStyleSheet("border: none;")
        self.collapse_file_choice_button.setText("")
        self.collapse_file_choice_button.setArrowType(QtCore.Qt.DownArrow)
        self.collapse_file_choice_button.setObjectName("collapse_file_choice_button")
        self.horizontalLayout_3.addWidget(self.collapse_file_choice_button)
        self.label_20 = QtWidgets.QLabel(self.file_panel_frame)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.file_choice_panel = QtWidgets.QWidget(self.file_panel_frame)
        self.file_choice_panel.setObjectName("file_choice_panel")
        self.file_grid = QtWidgets.QGridLayout(self.file_choice_panel)
        self.file_grid.setObjectName("file_grid")
        self.add_file_button = QtWidgets.QPushButton(self.file_choice_panel)
        self.add_file_button.setObjectName("add_file_button")
        self.file_grid.addWidget(self.add_file_button, 1, 0, 1, 1)
        self.file_table_widget = QtWidgets.QTableWidget(self.file_choice_panel)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.file_table_widget.setFont(font)
        self.file_table_widget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.file_table_widget.setShowGrid(False)
        self.file_table_widget.setCornerButtonEnabled(False)
        self.file_table_widget.setObjectName("file_table_widget")
        self.file_table_widget.setColumnCount(0)
        self.file_table_widget.setRowCount(0)
        self.file_table_widget.horizontalHeader().setVisible(False)
        self.file_table_widget.verticalHeader().setVisible(False)
        self.file_grid.addWidget(self.file_table_widget, 0, 0, 1, 2)
        self.remove_file_button = QtWidgets.QPushButton(self.file_choice_panel)
        self.remove_file_button.setObjectName("remove_file_button")
        self.file_grid.addWidget(self.remove_file_button, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.file_choice_panel)
        self.verticalLayout_12.addWidget(self.file_panel_frame)
        self.pane_panel_frame = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.pane_panel_frame.setObjectName("pane_panel_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pane_panel_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.collapse_pane_button = QtWidgets.QToolButton(self.pane_panel_frame)
        self.collapse_pane_button.setMinimumSize(QtCore.QSize(12, 12))
        self.collapse_pane_button.setMaximumSize(QtCore.QSize(12, 12))
        self.collapse_pane_button.setStyleSheet("border: none;")
        self.collapse_pane_button.setText("")
        self.collapse_pane_button.setArrowType(QtCore.Qt.DownArrow)
        self.collapse_pane_button.setObjectName("collapse_pane_button")
        self.horizontalLayout_5.addWidget(self.collapse_pane_button)
        self.label_19 = QtWidgets.QLabel(self.pane_panel_frame)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_5.addWidget(self.label_19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.pane_panel = QtWidgets.QWidget(self.pane_panel_frame)
        self.pane_panel.setObjectName("pane_panel")
        self.pane_grid = QtWidgets.QGridLayout(self.pane_panel)
        self.pane_grid.setObjectName("pane_grid")
        self.pane_tree_display = QtWidgets.QTreeWidget(self.pane_panel)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pane_tree_display.setFont(font)
        self.pane_tree_display.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.pane_tree_display.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.pane_tree_display.setRootIsDecorated(True)
        self.pane_tree_display.setExpandsOnDoubleClick(False)
        self.pane_tree_display.setObjectName("pane_tree_display")
        self.pane_tree_display.header().setVisible(False)
        self.pane_grid.addWidget(self.pane_tree_display, 2, 0, 1, 2)
        self.add_pane_button = QtWidgets.QPushButton(self.pane_panel)
        self.add_pane_button.setObjectName("add_pane_button")
        self.pane_grid.addWidget(self.add_pane_button, 3, 0, 1, 1)
        self.hightlight_pane_checkbox = QtWidgets.QCheckBox(self.pane_panel)
        self.hightlight_pane_checkbox.setChecked(True)
        self.hightlight_pane_checkbox.setObjectName("hightlight_pane_checkbox")
        self.pane_grid.addWidget(self.hightlight_pane_checkbox, 4, 0, 1, 2)
        self.remove_pane_button = QtWidgets.QPushButton(self.pane_panel)
        self.remove_pane_button.setObjectName("remove_pane_button")
        self.pane_grid.addWidget(self.remove_pane_button, 3, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.pane_panel)
        self.verticalLayout_12.addWidget(self.pane_panel_frame)
        self.order_panel_frame = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.order_panel_frame.setObjectName("order_panel_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.order_panel_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.collapse_order_button = QtWidgets.QToolButton(self.order_panel_frame)
        self.collapse_order_button.setMinimumSize(QtCore.QSize(12, 12))
        self.collapse_order_button.setMaximumSize(QtCore.QSize(12, 12))
        self.collapse_order_button.setStyleSheet("border: none;")
        self.collapse_order_button.setText("")
        self.collapse_order_button.setArrowType(QtCore.Qt.RightArrow)
        self.collapse_order_button.setObjectName("collapse_order_button")
        self.horizontalLayout_6.addWidget(self.collapse_order_button)
        self.label_15 = QtWidgets.QLabel(self.order_panel_frame)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.order_panel = QtWidgets.QWidget(self.order_panel_frame)
        self.order_panel.setObjectName("order_panel")
        self.order_grid = QtWidgets.QGridLayout(self.order_panel)
        self.order_grid.setObjectName("order_grid")
        self.remove_order_button = QtWidgets.QPushButton(self.order_panel)
        self.remove_order_button.setObjectName("remove_order_button")
        self.order_grid.addWidget(self.remove_order_button, 2, 1, 1, 1)
        self.order_list_widget = QtWidgets.QListWidget(self.order_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.order_list_widget.sizePolicy().hasHeightForWidth())
        self.order_list_widget.setSizePolicy(sizePolicy)
        self.order_list_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.order_list_widget.setFont(font)
        self.order_list_widget.setObjectName("order_list_widget")
        self.order_grid.addWidget(self.order_list_widget, 1, 0, 1, 2)
        self.add_order_button = QtWidgets.QPushButton(self.order_panel)
        self.add_order_button.setObjectName("add_order_button")
        self.order_grid.addWidget(self.add_order_button, 2, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.order_panel)
        self.verticalLayout_12.addWidget(self.order_panel_frame)
        self.analysis_panel_frame = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.analysis_panel_frame.setObjectName("analysis_panel_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.analysis_panel_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.collapse_analysis_button = QtWidgets.QToolButton(self.analysis_panel_frame)
        self.collapse_analysis_button.setMinimumSize(QtCore.QSize(12, 12))
        self.collapse_analysis_button.setMaximumSize(QtCore.QSize(12, 12))
        self.collapse_analysis_button.setStyleSheet("border: none;")
        self.collapse_analysis_button.setText("")
        self.collapse_analysis_button.setArrowType(QtCore.Qt.RightArrow)
        self.collapse_analysis_button.setObjectName("collapse_analysis_button")
        self.horizontalLayout_14.addWidget(self.collapse_analysis_button)
        self.label_46 = QtWidgets.QLabel(self.analysis_panel_frame)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_14.addWidget(self.label_46)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.analysis_panel = QtWidgets.QWidget(self.analysis_panel_frame)
        self.analysis_panel.setObjectName("analysis_panel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.analysis_panel)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_45 = QtWidgets.QLabel(self.analysis_panel)
        self.label_45.setObjectName("label_45")
        self.gridLayout_3.addWidget(self.label_45, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.analysis_panel)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.background_model_selection = QtWidgets.QComboBox(self.analysis_panel)
        self.background_model_selection.setObjectName("background_model_selection")
        self.background_model_selection.addItem("")
        self.background_model_selection.addItem("")
        self.background_model_selection.addItem("")
        self.gridLayout_3.addWidget(self.background_model_selection, 2, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.analysis_panel)
        self.label_47.setObjectName("label_47")
        self.gridLayout_3.addWidget(self.label_47, 0, 0, 1, 1)
        self.feature_model_selection = QtWidgets.QComboBox(self.analysis_panel)
        self.feature_model_selection.setObjectName("feature_model_selection")
        self.feature_model_selection.addItem("")
        self.feature_model_selection.addItem("")
        self.feature_model_selection.addItem("")
        self.gridLayout_3.addWidget(self.feature_model_selection, 1, 1, 1, 1)
        self.open_fit_results_button = QtWidgets.QPushButton(self.analysis_panel)
        self.open_fit_results_button.setObjectName("open_fit_results_button")
        self.gridLayout_3.addWidget(self.open_fit_results_button, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.analysis_panel)
        self.verticalLayout_12.addWidget(self.analysis_panel_frame)
        self.axis_panel_frame = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.axis_panel_frame.setObjectName("axis_panel_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.axis_panel_frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.collapse_axis_button = QtWidgets.QToolButton(self.axis_panel_frame)
        self.collapse_axis_button.setMinimumSize(QtCore.QSize(12, 12))
        self.collapse_axis_button.setMaximumSize(QtCore.QSize(12, 12))
        self.collapse_axis_button.setStyleSheet("border: none;")
        self.collapse_axis_button.setText("")
        self.collapse_axis_button.setArrowType(QtCore.Qt.RightArrow)
        self.collapse_axis_button.setObjectName("collapse_axis_button")
        self.horizontalLayout_7.addWidget(self.collapse_axis_button)
        self.label_14 = QtWidgets.QLabel(self.axis_panel_frame)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.axis_panel = QtWidgets.QWidget(self.axis_panel_frame)
        self.axis_panel.setObjectName("axis_panel")
        self.axis_grid = QtWidgets.QGridLayout(self.axis_panel)
        self.axis_grid.setObjectName("axis_grid")
        self.x_limit_min = QtWidgets.QLineEdit(self.axis_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_limit_min.sizePolicy().hasHeightForWidth())
        self.x_limit_min.setSizePolicy(sizePolicy)
        self.x_limit_min.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.x_limit_min.setObjectName("x_limit_min")
        self.axis_grid.addWidget(self.x_limit_min, 8, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.axis_panel)
        self.label_22.setObjectName("label_22")
        self.axis_grid.addWidget(self.label_22, 13, 0, 1, 1)
        self.x_unit_selector = QtWidgets.QComboBox(self.axis_panel)
        self.x_unit_selector.setObjectName("x_unit_selector")
        self.axis_grid.addWidget(self.x_unit_selector, 6, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.axis_panel)
        self.label_23.setObjectName("label_23")
        self.axis_grid.addWidget(self.label_23, 14, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.axis_panel)
        self.label_10.setObjectName("label_10")
        self.axis_grid.addWidget(self.label_10, 7, 0, 1, 1)
        self.y_limit_min = QtWidgets.QLineEdit(self.axis_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_limit_min.sizePolicy().hasHeightForWidth())
        self.y_limit_min.setSizePolicy(sizePolicy)
        self.y_limit_min.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.y_limit_min.setObjectName("y_limit_min")
        self.axis_grid.addWidget(self.y_limit_min, 10, 1, 1, 1)
        self.x_limit_max = QtWidgets.QLineEdit(self.axis_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_limit_max.sizePolicy().hasHeightForWidth())
        self.x_limit_max.setSizePolicy(sizePolicy)
        self.x_limit_max.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.x_limit_max.setObjectName("x_limit_max")
        self.axis_grid.addWidget(self.x_limit_max, 9, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.axis_panel)
        self.label_4.setObjectName("label_4")
        self.axis_grid.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.axis_panel)
        self.label_3.setObjectName("label_3")
        self.axis_grid.addWidget(self.label_3, 6, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.x_scale_linear_button = QtWidgets.QRadioButton(self.axis_panel)
        self.x_scale_linear_button.setChecked(True)
        self.x_scale_linear_button.setObjectName("x_scale_linear_button")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.x_scale_linear_button)
        self.gridLayout_9.addWidget(self.x_scale_linear_button, 1, 0, 1, 1)
        self.x_scale_log_button = QtWidgets.QRadioButton(self.axis_panel)
        self.x_scale_log_button.setObjectName("x_scale_log_button")
        self.buttonGroup_2.addButton(self.x_scale_log_button)
        self.gridLayout_9.addWidget(self.x_scale_log_button, 1, 1, 1, 1)
        self.axis_grid.addLayout(self.gridLayout_9, 13, 1, 1, 1)
        self.y_unit_selector = QtWidgets.QComboBox(self.axis_panel)
        self.y_unit_selector.setObjectName("y_unit_selector")
        self.axis_grid.addWidget(self.y_unit_selector, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.axis_panel)
        self.label_9.setObjectName("label_9")
        self.axis_grid.addWidget(self.label_9, 4, 0, 1, 1)
        self.y_property_selector = QtWidgets.QComboBox(self.axis_panel)
        self.y_property_selector.setObjectName("y_property_selector")
        self.axis_grid.addWidget(self.y_property_selector, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.axis_panel)
        self.label.setObjectName("label")
        self.axis_grid.addWidget(self.label, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.axis_panel)
        self.label_17.setObjectName("label_17")
        self.axis_grid.addWidget(self.label_17, 10, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.axis_panel)
        self.label_16.setObjectName("label_16")
        self.axis_grid.addWidget(self.label_16, 8, 0, 1, 1)
        self.y_limit_max = QtWidgets.QLineEdit(self.axis_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_limit_max.sizePolicy().hasHeightForWidth())
        self.y_limit_max.setSizePolicy(sizePolicy)
        self.y_limit_max.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.y_limit_max.setObjectName("y_limit_max")
        self.axis_grid.addWidget(self.y_limit_max, 11, 1, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.y_scale_linear_button = QtWidgets.QRadioButton(self.axis_panel)
        self.y_scale_linear_button.setChecked(True)
        self.y_scale_linear_button.setObjectName("y_scale_linear_button")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.y_scale_linear_button)
        self.gridLayout_10.addWidget(self.y_scale_linear_button, 0, 0, 1, 1)
        self.y_scale_log_button = QtWidgets.QRadioButton(self.axis_panel)
        self.y_scale_log_button.setObjectName("y_scale_log_button")
        self.buttonGroup.addButton(self.y_scale_log_button)
        self.gridLayout_10.addWidget(self.y_scale_log_button, 0, 1, 1, 1)
        self.axis_grid.addLayout(self.gridLayout_10, 14, 1, 1, 1)
        self.x_property_selector = QtWidgets.QComboBox(self.axis_panel)
        self.x_property_selector.setObjectName("x_property_selector")
        self.axis_grid.addWidget(self.x_property_selector, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.axis_panel)
        self.label_2.setObjectName("label_2")
        self.axis_grid.addWidget(self.label_2, 16, 0, 1, 1)
        self.axes_selector = QtWidgets.QComboBox(self.axis_panel)
        self.axes_selector.setObjectName("axes_selector")
        self.axes_selector.addItem("")
        self.axes_selector.addItem("")
        self.axes_selector.addItem("")
        self.axes_selector.addItem("")
        self.axes_selector.addItem("")
        self.axis_grid.addWidget(self.axes_selector, 2, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.x_zoom_button = QtWidgets.QPushButton(self.axis_panel)
        self.x_zoom_button.setObjectName("x_zoom_button")
        self.horizontalLayout.addWidget(self.x_zoom_button)
        self.y_zoom_button = QtWidgets.QPushButton(self.axis_panel)
        self.y_zoom_button.setObjectName("y_zoom_button")
        self.horizontalLayout.addWidget(self.y_zoom_button)
        self.box_zoom_button = QtWidgets.QPushButton(self.axis_panel)
        self.box_zoom_button.setObjectName("box_zoom_button")
        self.horizontalLayout.addWidget(self.box_zoom_button)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.reset_zoom_button = QtWidgets.QPushButton(self.axis_panel)
        self.reset_zoom_button.setObjectName("reset_zoom_button")
        self.horizontalLayout_9.addWidget(self.reset_zoom_button)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.axis_grid.addLayout(self.verticalLayout_10, 16, 1, 1, 1)
        self.enable_overplot_checkbox = QtWidgets.QCheckBox(self.axis_panel)
        self.enable_overplot_checkbox.setObjectName("enable_overplot_checkbox")
        self.axis_grid.addWidget(self.enable_overplot_checkbox, 12, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.axis_panel)
        self.label_24.setObjectName("label_24")
        self.axis_grid.addWidget(self.label_24, 12, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.axis_panel)
        self.verticalLayout_12.addWidget(self.axis_panel_frame)
        self.plot_panel_frame = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.plot_panel_frame.setObjectName("plot_panel_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.plot_panel_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.collapse_plot_button = QtWidgets.QToolButton(self.plot_panel_frame)
        self.collapse_plot_button.setMinimumSize(QtCore.QSize(12, 12))
        self.collapse_plot_button.setMaximumSize(QtCore.QSize(12, 12))
        self.collapse_plot_button.setStyleSheet("border: none;")
        self.collapse_plot_button.setText("")
        self.collapse_plot_button.setArrowType(QtCore.Qt.RightArrow)
        self.collapse_plot_button.setObjectName("collapse_plot_button")
        self.horizontalLayout_2.addWidget(self.collapse_plot_button)
        self.label_5 = QtWidgets.QLabel(self.plot_panel_frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.plot_panel = QtWidgets.QWidget(self.plot_panel_frame)
        self.plot_panel.setObjectName("plot_panel")
        self.gridLayout = QtWidgets.QGridLayout(self.plot_panel)
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setObjectName("gridLayout")
        self.color_cycle_selector = QtWidgets.QComboBox(self.plot_panel)
        self.color_cycle_selector.setObjectName("color_cycle_selector")
        self.color_cycle_selector.addItem("")
        self.color_cycle_selector.addItem("")
        self.color_cycle_selector.addItem("")
        self.gridLayout.addWidget(self.color_cycle_selector, 0, 2, 1, 1)
        self.plot_type_selector = QtWidgets.QComboBox(self.plot_panel)
        self.plot_type_selector.setObjectName("plot_type_selector")
        self.plot_type_selector.addItem("")
        self.plot_type_selector.addItem("")
        self.plot_type_selector.addItem("")
        self.gridLayout.addWidget(self.plot_type_selector, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.plot_panel)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 1, 1, 1, 1)
        self.marker_checkbox = QtWidgets.QCheckBox(self.plot_panel)
        self.marker_checkbox.setObjectName("marker_checkbox")
        self.gridLayout.addWidget(self.marker_checkbox, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.plot_panel)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 1, 1, 1)
        self.grid_checkbox = QtWidgets.QCheckBox(self.plot_panel)
        self.grid_checkbox.setObjectName("grid_checkbox")
        self.gridLayout.addWidget(self.grid_checkbox, 3, 1, 1, 1)
        self.error_checkbox = QtWidgets.QCheckBox(self.plot_panel)
        self.error_checkbox.setChecked(True)
        self.error_checkbox.setObjectName("error_checkbox")
        self.gridLayout.addWidget(self.error_checkbox, 2, 2, 1, 1)
        self.dark_mode_checkbox = QtWidgets.QCheckBox(self.plot_panel)
        self.dark_mode_checkbox.setObjectName("dark_mode_checkbox")
        self.gridLayout.addWidget(self.dark_mode_checkbox, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.plot_panel)
        self.verticalLayout_12.addWidget(self.plot_panel_frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.figure_grid = QtWidgets.QGridLayout(self.layoutWidget)
        self.figure_grid.setContentsMargins(0, 0, 0, 0)
        self.figure_grid.setHorizontalSpacing(0)
        self.figure_grid.setVerticalSpacing(1)
        self.figure_grid.setObjectName("figure_grid")
        self.collapse_cursor_button = QtWidgets.QToolButton(self.layoutWidget)
        self.collapse_cursor_button.setMinimumSize(QtCore.QSize(12, 12))
        self.collapse_cursor_button.setMaximumSize(QtCore.QSize(12, 12))
        self.collapse_cursor_button.setStyleSheet("border: none;")
        self.collapse_cursor_button.setText("")
        self.collapse_cursor_button.setArrowType(QtCore.Qt.DownArrow)
        self.collapse_cursor_button.setObjectName("collapse_cursor_button")
        self.figure_grid.addWidget(self.collapse_cursor_button, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.cursor_frame = QtWidgets.QGroupBox(self.layoutWidget)
        self.cursor_frame.setTitle("")
        self.cursor_frame.setObjectName("cursor_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cursor_frame)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 3, 1, 1)
        self.cursor_x_label = QtWidgets.QLabel(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursor_x_label.sizePolicy().hasHeightForWidth())
        self.cursor_x_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cursor_x_label.setFont(font)
        self.cursor_x_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cursor_x_label.setObjectName("cursor_x_label")
        self.gridLayout_2.addWidget(self.cursor_x_label, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.cursor_checkbox = QtWidgets.QCheckBox(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursor_checkbox.sizePolicy().hasHeightForWidth())
        self.cursor_checkbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cursor_checkbox.setFont(font)
        self.cursor_checkbox.setObjectName("cursor_checkbox")
        self.gridLayout_2.addWidget(self.cursor_checkbox, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.cursor_wave_label = QtWidgets.QLabel(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursor_wave_label.sizePolicy().hasHeightForWidth())
        self.cursor_wave_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cursor_wave_label.setFont(font)
        self.cursor_wave_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cursor_wave_label.setObjectName("cursor_wave_label")
        self.gridLayout_2.addWidget(self.cursor_wave_label, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.cursor_y_label = QtWidgets.QLabel(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursor_y_label.sizePolicy().hasHeightForWidth())
        self.cursor_y_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cursor_y_label.setFont(font)
        self.cursor_y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cursor_y_label.setObjectName("cursor_y_label")
        self.gridLayout_2.addWidget(self.cursor_y_label, 1, 1, 1, 1)
        self.cursor_column_label = QtWidgets.QLabel(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursor_column_label.sizePolicy().hasHeightForWidth())
        self.cursor_column_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cursor_column_label.setFont(font)
        self.cursor_column_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cursor_column_label.setObjectName("cursor_column_label")
        self.gridLayout_2.addWidget(self.cursor_column_label, 1, 4, 1, 1)
        self.cursor_popout_button = QtWidgets.QPushButton(self.cursor_frame)
        self.cursor_popout_button.setObjectName("cursor_popout_button")
        self.gridLayout_2.addWidget(self.cursor_popout_button, 1, 5, 1, 1)
        self.cursor_flux_label = QtWidgets.QLabel(self.cursor_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursor_flux_label.sizePolicy().hasHeightForWidth())
        self.cursor_flux_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cursor_flux_label.setFont(font)
        self.cursor_flux_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cursor_flux_label.setObjectName("cursor_flux_label")
        self.gridLayout_2.addWidget(self.cursor_flux_label, 1, 3, 1, 1)
        self.figure_grid.addWidget(self.cursor_frame, 2, 1, 1, 1)
        self.collapse_controls_button = QtWidgets.QToolButton(self.layoutWidget)
        self.collapse_controls_button.setMinimumSize(QtCore.QSize(12, 12))
        self.collapse_controls_button.setMaximumSize(QtCore.QSize(12, 12))
        self.collapse_controls_button.setStyleSheet("border: none;")
        self.collapse_controls_button.setText("")
        self.collapse_controls_button.setArrowType(QtCore.Qt.LeftArrow)
        self.collapse_controls_button.setObjectName("collapse_controls_button")
        self.figure_grid.addWidget(self.collapse_controls_button, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.figure_widget = MplWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.figure_widget.sizePolicy().hasHeightForWidth())
        self.figure_widget.setSizePolicy(sizePolicy)
        self.figure_widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.figure_widget.setObjectName("figure_widget")
        self.figure_grid.addWidget(self.figure_widget, 0, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 22))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_display = QtWidgets.QMenu(self.menubar)
        self.menu_display.setObjectName("menu_display")
        self.menuX_scale = QtWidgets.QMenu(self.menu_display)
        self.menuX_scale.setObjectName("menuX_scale")
        self.menuY_scale = QtWidgets.QMenu(self.menu_display)
        self.menuY_scale.setObjectName("menuY_scale")
        self.menu_zoom = QtWidgets.QMenu(self.menu_display)
        self.menu_zoom.setObjectName("menu_zoom")
        self.menu_analysis = QtWidgets.QMenu(self.menubar)
        self.menu_analysis.setObjectName("menu_analysis")
        self.menu_fits = QtWidgets.QMenu(self.menu_analysis)
        self.menu_fits.setObjectName("menu_fits")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAxes_Limits = QtWidgets.QAction(MainWindow)
        self.actionAxes_Limits.setObjectName("actionAxes_Limits")
        self.actionLinear_x = QtWidgets.QAction(MainWindow)
        self.actionLinear_x.setObjectName("actionLinear_x")
        self.actionLog_x = QtWidgets.QAction(MainWindow)
        self.actionLog_x.setObjectName("actionLog_x")
        self.actionLinear_y = QtWidgets.QAction(MainWindow)
        self.actionLinear_y.setObjectName("actionLinear_y")
        self.actionLog_y = QtWidgets.QAction(MainWindow)
        self.actionLog_y.setObjectName("actionLog_y")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionmicron = QtWidgets.QAction(MainWindow)
        self.actionmicron.setObjectName("actionmicron")
        self.actionnm = QtWidgets.QAction(MainWindow)
        self.actionnm.setObjectName("actionnm")
        self.actionA = QtWidgets.QAction(MainWindow)
        self.actionA.setObjectName("actionA")
        self.actionpixels = QtWidgets.QAction(MainWindow)
        self.actionpixels.setObjectName("actionpixels")
        self.actionW_m_2_um_1 = QtWidgets.QAction(MainWindow)
        self.actionW_m_2_um_1.setObjectName("actionW_m_2_um_1")
        self.actionergs_s_1_cm_2_A_1 = QtWidgets.QAction(MainWindow)
        self.actionergs_s_1_cm_2_A_1.setObjectName("actionergs_s_1_cm_2_A_1")
        self.actionW_m_2_Hz_1 = QtWidgets.QAction(MainWindow)
        self.actionW_m_2_Hz_1.setObjectName("actionW_m_2_Hz_1")
        self.actionergs_s_1_cm_2_Hz_1 = QtWidgets.QAction(MainWindow)
        self.actionergs_s_1_cm_2_Hz_1.setObjectName("actionergs_s_1_cm_2_Hz_1")
        self.actionJy = QtWidgets.QAction(MainWindow)
        self.actionJy.setObjectName("actionJy")
        self.actionW_m_2 = QtWidgets.QAction(MainWindow)
        self.actionW_m_2.setObjectName("actionW_m_2")
        self.actionergs_s_1_cm_2 = QtWidgets.QAction(MainWindow)
        self.actionergs_s_1_cm_2.setObjectName("actionergs_s_1_cm_2")
        self.actionFlux = QtWidgets.QAction(MainWindow)
        self.actionFlux.setObjectName("actionFlux")
        self.actionUncertainty = QtWidgets.QAction(MainWindow)
        self.actionUncertainty.setObjectName("actionUncertainty")
        self.actionS_N = QtWidgets.QAction(MainWindow)
        self.actionS_N.setObjectName("actionS_N")
        self.actionTransmission = QtWidgets.QAction(MainWindow)
        self.actionTransmission.setObjectName("actionTransmission")
        self.actionResponse = QtWidgets.QAction(MainWindow)
        self.actionResponse.setObjectName("actionResponse")
        self.actionWavelength = QtWidgets.QAction(MainWindow)
        self.actionWavelength.setObjectName("actionWavelength")
        self.actionPixels = QtWidgets.QAction(MainWindow)
        self.actionPixels.setObjectName("actionPixels")
        self.actionView_FITS_Header = QtWidgets.QAction(MainWindow)
        self.actionView_FITS_Header.setObjectName("actionView_FITS_Header")
        self.action_zoom_y = QtWidgets.QAction(MainWindow)
        self.action_zoom_y.setObjectName("action_zoom_y")
        self.action_zoom_x = QtWidgets.QAction(MainWindow)
        self.action_zoom_x.setObjectName("action_zoom_x")
        self.action_zoom_box = QtWidgets.QAction(MainWindow)
        self.action_zoom_box.setObjectName("action_zoom_box")
        self.actionGaussian = QtWidgets.QAction(MainWindow)
        self.actionGaussian.setObjectName("actionGaussian")
        self.action_gaussian = QtWidgets.QAction(MainWindow)
        self.action_gaussian.setObjectName("action_gaussian")
        self.action_zoom_reset = QtWidgets.QAction(MainWindow)
        self.action_zoom_reset.setObjectName("action_zoom_reset")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionView_FITS_Header)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuX_scale.addSeparator()
        self.menuX_scale.addAction(self.actionLinear_x)
        self.menuX_scale.addAction(self.actionLog_x)
        self.menuX_scale.addSeparator()
        self.menuX_scale.addAction(self.actionmicron)
        self.menuX_scale.addAction(self.actionnm)
        self.menuX_scale.addAction(self.actionA)
        self.menuX_scale.addAction(self.actionpixels)
        self.menuX_scale.addSeparator()
        self.menuY_scale.addAction(self.actionLinear_y)
        self.menuY_scale.addAction(self.actionLog_y)
        self.menuY_scale.addSeparator()
        self.menuY_scale.addAction(self.actionW_m_2_um_1)
        self.menuY_scale.addAction(self.actionergs_s_1_cm_2_A_1)
        self.menuY_scale.addAction(self.actionW_m_2_Hz_1)
        self.menuY_scale.addAction(self.actionergs_s_1_cm_2_Hz_1)
        self.menuY_scale.addAction(self.actionJy)
        self.menuY_scale.addAction(self.actionW_m_2)
        self.menuY_scale.addAction(self.actionergs_s_1_cm_2)
        self.menu_zoom.addAction(self.action_zoom_x)
        self.menu_zoom.addAction(self.action_zoom_y)
        self.menu_zoom.addAction(self.action_zoom_box)
        self.menu_zoom.addAction(self.action_zoom_reset)
        self.menu_display.addAction(self.actionAxes_Limits)
        self.menu_display.addSeparator()
        self.menu_display.addAction(self.menuX_scale.menuAction())
        self.menu_display.addAction(self.menuY_scale.menuAction())
        self.menu_display.addSeparator()
        self.menu_display.addAction(self.actionFlux)
        self.menu_display.addAction(self.actionUncertainty)
        self.menu_display.addAction(self.actionS_N)
        self.menu_display.addAction(self.actionTransmission)
        self.menu_display.addAction(self.actionResponse)
        self.menu_display.addSeparator()
        self.menu_display.addAction(self.actionWavelength)
        self.menu_display.addAction(self.actionPixels)
        self.menu_display.addSeparator()
        self.menu_display.addAction(self.menu_zoom.menuAction())
        self.menu_fits.addAction(self.action_gaussian)
        self.menu_analysis.addAction(self.menu_fits.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_display.menuAction())
        self.menubar.addAction(self.menu_analysis.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.x_scale_linear_button, self.x_scale_log_button)
        MainWindow.setTabOrder(self.x_scale_log_button, self.file_table_widget)
        MainWindow.setTabOrder(self.file_table_widget, self.y_scale_linear_button)
        MainWindow.setTabOrder(self.y_scale_linear_button, self.y_scale_log_button)
        MainWindow.setTabOrder(self.y_scale_log_button, self.add_file_button)
        MainWindow.setTabOrder(self.add_file_button, self.remove_file_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "The Eye of SOFIA"))
        self.collapse_file_choice_button.setToolTip(_translate("MainWindow", "Hide cursor panel"))
        self.label_20.setText(_translate("MainWindow", "File Choice"))
        self.add_file_button.setText(_translate("MainWindow", "Add File"))
        self.file_table_widget.setSortingEnabled(True)
        self.remove_file_button.setText(_translate("MainWindow", "Remove File"))
        self.collapse_pane_button.setToolTip(_translate("MainWindow", "Hide pane panel"))
        self.label_19.setText(_translate("MainWindow", "Panes"))
        self.add_pane_button.setText(_translate("MainWindow", "Add Pane"))
        self.hightlight_pane_checkbox.setText(_translate("MainWindow", "Highlight Current Pane"))
        self.remove_pane_button.setText(_translate("MainWindow", "Remove Pane"))
        self.collapse_order_button.setToolTip(_translate("MainWindow", "Show order panel"))
        self.label_15.setText(_translate("MainWindow", "Orders"))
        self.remove_order_button.setText(_translate("MainWindow", "Remove Order"))
        self.add_order_button.setText(_translate("MainWindow", "Add Order"))
        self.collapse_analysis_button.setToolTip(_translate("MainWindow", "Show analysis panel"))
        self.label_46.setText(_translate("MainWindow", "Analysis"))
        self.label_45.setText(_translate("MainWindow", "Background"))
        self.label_18.setText(_translate("MainWindow", "Feature"))
        self.background_model_selection.setItemText(0, _translate("MainWindow", "Linear"))
        self.background_model_selection.setItemText(1, _translate("MainWindow", "Constant"))
        self.background_model_selection.setItemText(2, _translate("MainWindow", "-"))
        self.label_47.setText(_translate("MainWindow", "Fitting"))
        self.feature_model_selection.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.feature_model_selection.setItemText(1, _translate("MainWindow", "Moffat"))
        self.feature_model_selection.setItemText(2, _translate("MainWindow", "-"))
        self.open_fit_results_button.setText(_translate("MainWindow", "Open Fit Results"))
        self.collapse_axis_button.setToolTip(_translate("MainWindow", "Show axis panel"))
        self.label_14.setText(_translate("MainWindow", "Axis"))
        self.label_22.setText(_translate("MainWindow", "X Scale"))
        self.label_23.setText(_translate("MainWindow", "Y Scale"))
        self.label_10.setText(_translate("MainWindow", "Y Unit"))
        self.label_4.setText(_translate("MainWindow", "Y Field"))
        self.label_3.setText(_translate("MainWindow", "X Unit"))
        self.x_scale_linear_button.setText(_translate("MainWindow", "Linear"))
        self.x_scale_log_button.setText(_translate("MainWindow", "Log"))
        self.label_9.setText(_translate("MainWindow", "X Field"))
        self.label.setText(_translate("MainWindow", "Apply to:"))
        self.label_17.setText(_translate("MainWindow", "Y Limits"))
        self.label_16.setText(_translate("MainWindow", "X Limits"))
        self.y_scale_linear_button.setText(_translate("MainWindow", "Linear"))
        self.y_scale_log_button.setText(_translate("MainWindow", "Log"))
        self.label_2.setText(_translate("MainWindow", "Zoom"))
        self.axes_selector.setItemText(0, _translate("MainWindow", "Current Primary"))
        self.axes_selector.setItemText(1, _translate("MainWindow", "Current Overplot"))
        self.axes_selector.setItemText(2, _translate("MainWindow", "All Primary"))
        self.axes_selector.setItemText(3, _translate("MainWindow", "All Overplots"))
        self.axes_selector.setItemText(4, _translate("MainWindow", "All"))
        self.x_zoom_button.setText(_translate("MainWindow", "X"))
        self.y_zoom_button.setText(_translate("MainWindow", "Y"))
        self.box_zoom_button.setText(_translate("MainWindow", "Box"))
        self.reset_zoom_button.setText(_translate("MainWindow", "Reset"))
        self.enable_overplot_checkbox.setText(_translate("MainWindow", "Enabled"))
        self.label_24.setText(_translate("MainWindow", "Overplot"))
        self.collapse_plot_button.setToolTip(_translate("MainWindow", "Show plot panel"))
        self.label_5.setText(_translate("MainWindow", "Plot"))
        self.color_cycle_selector.setItemText(0, _translate("MainWindow", "Accessible"))
        self.color_cycle_selector.setItemText(1, _translate("MainWindow", "Spectral"))
        self.color_cycle_selector.setItemText(2, _translate("MainWindow", "Tableau"))
        self.plot_type_selector.setItemText(0, _translate("MainWindow", "Step"))
        self.plot_type_selector.setItemText(1, _translate("MainWindow", "Line"))
        self.plot_type_selector.setItemText(2, _translate("MainWindow", "Scatter"))
        self.label_21.setText(_translate("MainWindow", "Plot type"))
        self.marker_checkbox.setText(_translate("MainWindow", "Show markers"))
        self.label_13.setText(_translate("MainWindow", "Color cycle "))
        self.grid_checkbox.setText(_translate("MainWindow", "Show grid"))
        self.error_checkbox.setText(_translate("MainWindow", "Show errors"))
        self.dark_mode_checkbox.setText(_translate("MainWindow", "Dark mode"))
        self.collapse_cursor_button.setToolTip(_translate("MainWindow", "Hide cursor panel"))
        self.label_12.setText(_translate("MainWindow", "Y Value"))
        self.cursor_x_label.setToolTip(_translate("MainWindow", "Hide file choice panel"))
        self.cursor_x_label.setText(_translate("MainWindow", "-"))
        self.label_8.setText(_translate("MainWindow", "Column"))
        self.label_11.setText(_translate("MainWindow", "Y Cursor"))
        self.cursor_checkbox.setText(_translate("MainWindow", "Cursor Location"))
        self.label_6.setText(_translate("MainWindow", "X Cursor"))
        self.cursor_wave_label.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "X Value"))
        self.cursor_y_label.setText(_translate("MainWindow", "-"))
        self.cursor_column_label.setText(_translate("MainWindow", "-"))
        self.cursor_popout_button.setText(_translate("MainWindow", "Popout"))
        self.cursor_flux_label.setText(_translate("MainWindow", "-"))
        self.collapse_controls_button.setToolTip(_translate("MainWindow", "Hide control panel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menu_display.setTitle(_translate("MainWindow", "Display"))
        self.menuX_scale.setTitle(_translate("MainWindow", "X axis"))
        self.menuY_scale.setTitle(_translate("MainWindow", "Y axis"))
        self.menu_zoom.setTitle(_translate("MainWindow", "Zoom"))
        self.menu_analysis.setTitle(_translate("MainWindow", "Analysis"))
        self.menu_fits.setTitle(_translate("MainWindow", "Fits"))
        self.actionOpen.setText(_translate("MainWindow", "Open FITS File"))
        self.actionAxes_Limits.setText(_translate("MainWindow", "Axes Limits"))
        self.actionLinear_x.setText(_translate("MainWindow", "Linear"))
        self.actionLog_x.setText(_translate("MainWindow", "Log"))
        self.actionLinear_y.setText(_translate("MainWindow", "Linear"))
        self.actionLog_y.setText(_translate("MainWindow", "Log"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionmicron.setText(_translate("MainWindow", "um"))
        self.actionnm.setText(_translate("MainWindow", "nm"))
        self.actionA.setText(_translate("MainWindow", "A"))
        self.actionpixels.setText(_translate("MainWindow", "pixels"))
        self.actionW_m_2_um_1.setText(_translate("MainWindow", "W m-2 um-1"))
        self.actionergs_s_1_cm_2_A_1.setText(_translate("MainWindow", "ergs s-1 cm-2 A-1"))
        self.actionW_m_2_Hz_1.setText(_translate("MainWindow", "W m-2 Hz-1"))
        self.actionergs_s_1_cm_2_Hz_1.setText(_translate("MainWindow", "ergs s-1 cm-2 Hz-1"))
        self.actionJy.setText(_translate("MainWindow", "Jy"))
        self.actionW_m_2.setText(_translate("MainWindow", "W m-2"))
        self.actionergs_s_1_cm_2.setText(_translate("MainWindow", "ergs s-1 cm-2"))
        self.actionFlux.setText(_translate("MainWindow", "Flux"))
        self.actionUncertainty.setText(_translate("MainWindow", "Uncertainty"))
        self.actionS_N.setText(_translate("MainWindow", "S/N"))
        self.actionTransmission.setText(_translate("MainWindow", "Transmission"))
        self.actionResponse.setText(_translate("MainWindow", "Response"))
        self.actionWavelength.setText(_translate("MainWindow", "Wavelength"))
        self.actionPixels.setText(_translate("MainWindow", "Pixels"))
        self.actionView_FITS_Header.setText(_translate("MainWindow", "View FITS Header"))
        self.action_zoom_y.setText(_translate("MainWindow", "Y"))
        self.action_zoom_x.setText(_translate("MainWindow", "X"))
        self.action_zoom_box.setText(_translate("MainWindow", "Box"))
        self.actionGaussian.setText(_translate("MainWindow", "Gaussian"))
        self.action_gaussian.setText(_translate("MainWindow", "Gaussian"))
        self.action_zoom_reset.setText(_translate("MainWindow", "Reset"))

from sofia_redux.visualization.display.ui.mplwidget import MplWidget
