# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 715)
        MainWindow.setStyleSheet("#statusbar {\n"
"    border-top: 1px solid rgb(183, 183, 183)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pipeStepContainer = QtWidgets.QWidget(self.centralwidget)
        self.pipeStepContainer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pipeStepContainer.sizePolicy().hasHeightForWidth())
        self.pipeStepContainer.setSizePolicy(sizePolicy)
        self.pipeStepContainer.setMinimumSize(QtCore.QSize(333, 0))
        self.pipeStepContainer.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pipeStepContainer.setObjectName("pipeStepContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pipeStepContainer)
        self.verticalLayout_3.setContentsMargins(0, 1, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pipelineVersionLabel = QtWidgets.QLabel(self.pipeStepContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pipelineVersionLabel.sizePolicy().hasHeightForWidth())
        self.pipelineVersionLabel.setSizePolicy(sizePolicy)
        self.pipelineVersionLabel.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pipelineVersionLabel.setFont(font)
        self.pipelineVersionLabel.setObjectName("pipelineVersionLabel")
        self.verticalLayout_3.addWidget(self.pipelineVersionLabel)
        self.fileSummaryTextEdit = QtWidgets.QTextEdit(self.pipeStepContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileSummaryTextEdit.sizePolicy().hasHeightForWidth())
        self.fileSummaryTextEdit.setSizePolicy(sizePolicy)
        self.fileSummaryTextEdit.setMinimumSize(QtCore.QSize(0, 130))
        self.fileSummaryTextEdit.setMaximumSize(QtCore.QSize(16777215, 130))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fileSummaryTextEdit.setFont(font)
        self.fileSummaryTextEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fileSummaryTextEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.fileSummaryTextEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.fileSummaryTextEdit.setPlaceholderText("")
        self.fileSummaryTextEdit.setObjectName("fileSummaryTextEdit")
        self.verticalLayout_3.addWidget(self.fileSummaryTextEdit)
        self.controlsBox = QtWidgets.QGroupBox(self.pipeStepContainer)
        self.controlsBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlsBox.sizePolicy().hasHeightForWidth())
        self.controlsBox.setSizePolicy(sizePolicy)
        self.controlsBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.controlsBox.setObjectName("controlsBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controlsBox)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stepControls = QtWidgets.QFrame(self.controlsBox)
        self.stepControls.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepControls.sizePolicy().hasHeightForWidth())
        self.stepControls.setSizePolicy(sizePolicy)
        self.stepControls.setMinimumSize(QtCore.QSize(0, 68))
        self.stepControls.setMaximumSize(QtCore.QSize(16777215, 68))
        self.stepControls.setObjectName("stepControls")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stepControls)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stepFrame = QtWidgets.QFrame(self.stepControls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepFrame.sizePolicy().hasHeightForWidth())
        self.stepFrame.setSizePolicy(sizePolicy)
        self.stepFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stepFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stepFrame.setObjectName("stepFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.stepFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stepButton = QtWidgets.QPushButton(self.stepFrame)
        self.stepButton.setEnabled(True)
        self.stepButton.setObjectName("stepButton")
        self.horizontalLayout_4.addWidget(self.stepButton)
        self.undoButton = QtWidgets.QPushButton(self.stepFrame)
        self.undoButton.setEnabled(True)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_4.addWidget(self.undoButton)
        self.reduceButton = QtWidgets.QPushButton(self.stepFrame)
        self.reduceButton.setEnabled(True)
        self.reduceButton.setObjectName("reduceButton")
        self.horizontalLayout_4.addWidget(self.reduceButton)
        self.resetButton = QtWidgets.QPushButton(self.stepFrame)
        self.resetButton.setEnabled(True)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_4.addWidget(self.resetButton)
        self.verticalLayout_2.addWidget(self.stepFrame)
        self.stepThroughFrame = QtWidgets.QWidget(self.stepControls)
        self.stepThroughFrame.setEnabled(True)
        self.stepThroughFrame.setObjectName("stepThroughFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.stepThroughFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.stepThroughFrame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.stepThroughComboBox = QtWidgets.QComboBox(self.stepThroughFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepThroughComboBox.sizePolicy().hasHeightForWidth())
        self.stepThroughComboBox.setSizePolicy(sizePolicy)
        self.stepThroughComboBox.setObjectName("stepThroughComboBox")
        self.stepThroughComboBox.addItem("")
        self.stepThroughComboBox.setItemText(0, "")
        self.horizontalLayout_2.addWidget(self.stepThroughComboBox)
        self.verticalLayout_2.addWidget(self.stepThroughFrame)
        self.verticalLayout.addWidget(self.stepControls)
        self.pipeStepFrame = QtWidgets.QScrollArea(self.controlsBox)
        self.pipeStepFrame.setEnabled(True)
        self.pipeStepFrame.setStyleSheet("")
        self.pipeStepFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pipeStepFrame.setWidgetResizable(True)
        self.pipeStepFrame.setObjectName("pipeStepFrame")
        self.pipeStepFrameWidget = QtWidgets.QWidget()
        self.pipeStepFrameWidget.setEnabled(True)
        self.pipeStepFrameWidget.setGeometry(QtCore.QRect(0, 0, 317, 377))
        self.pipeStepFrameWidget.setStyleSheet("")
        self.pipeStepFrameWidget.setObjectName("pipeStepFrameWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pipeStepFrameWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pipeStepListWidget = QtWidgets.QListWidget(self.pipeStepFrameWidget)
        self.pipeStepListWidget.setEnabled(True)
        self.pipeStepListWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pipeStepListWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pipeStepListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.pipeStepListWidget.setProperty("showDropIndicator", False)
        self.pipeStepListWidget.setAlternatingRowColors(True)
        self.pipeStepListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.pipeStepListWidget.setObjectName("pipeStepListWidget")
        self.gridLayout_5.addWidget(self.pipeStepListWidget, 0, 0, 1, 1)
        self.pipeStepFrame.setWidget(self.pipeStepFrameWidget)
        self.verticalLayout.addWidget(self.pipeStepFrame)
        self.verticalLayout_3.addWidget(self.controlsBox)
        self.horizontalLayout_3.addWidget(self.pipeStepContainer)
        self.dataTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTabWidget.sizePolicy().hasHeightForWidth())
        self.dataTabWidget.setSizePolicy(sizePolicy)
        self.dataTabWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.dataTabWidget.setObjectName("dataTabWidget")
        self.fileInfoTab = QtWidgets.QWidget()
        self.fileInfoTab.setObjectName("fileInfoTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fileInfoTab)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fileTableView = QtWidgets.QTableView(self.fileInfoTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fileTableView.setFont(font)
        self.fileTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fileTableView.setTabKeyNavigation(False)
        self.fileTableView.setProperty("showDropIndicator", False)
        self.fileTableView.setDragDropOverwriteMode(False)
        self.fileTableView.setAlternatingRowColors(True)
        self.fileTableView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.fileTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fileTableView.setSortingEnabled(True)
        self.fileTableView.setObjectName("fileTableView")
        self.fileTableView.horizontalHeader().setCascadingSectionResizes(False)
        self.fileTableView.horizontalHeader().setHighlightSections(False)
        self.fileTableView.horizontalHeader().setMinimumSectionSize(50)
        self.fileTableView.horizontalHeader().setStretchLastSection(True)
        self.fileTableView.verticalHeader().setVisible(False)
        self.fileTableView.verticalHeader().setHighlightSections(False)
        self.fileTableView.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.fileTableView, 0, 0, 1, 1)
        self.dataTabWidget.addTab(self.fileInfoTab, "")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.logTab)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.logTextEdit = QtWidgets.QTextEdit(self.logTab)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        font.setPointSize(12)
        self.logTextEdit.setFont(font)
        self.logTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.logTextEdit.setPlaceholderText("")
        self.logTextEdit.setObjectName("logTextEdit")
        self.gridLayout_4.addWidget(self.logTextEdit, 0, 0, 1, 1)
        self.dataTabWidget.addTab(self.logTab, "")
        self.horizontalLayout_3.addWidget(self.dataTabWidget)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 22))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuParameters = QtWidgets.QMenu(self.menubar)
        self.menuParameters.setObjectName("menuParameters")
        self.menuDisplay = QtWidgets.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpenNewReduction = QtWidgets.QAction(MainWindow)
        self.actionOpenNewReduction.setObjectName("actionOpenNewReduction")
        self.actionAddFiles = QtWidgets.QAction(MainWindow)
        self.actionAddFiles.setEnabled(False)
        self.actionAddFiles.setObjectName("actionAddFiles")
        self.actionRemoveFiles = QtWidgets.QAction(MainWindow)
        self.actionRemoveFiles.setEnabled(False)
        self.actionRemoveFiles.setObjectName("actionRemoveFiles")
        self.actionDisplayAllParameters = QtWidgets.QAction(MainWindow)
        self.actionDisplayAllParameters.setEnabled(False)
        self.actionDisplayAllParameters.setObjectName("actionDisplayAllParameters")
        self.actionLoadParameters = QtWidgets.QAction(MainWindow)
        self.actionLoadParameters.setEnabled(False)
        self.actionLoadParameters.setObjectName("actionLoadParameters")
        self.actionSaveParameters = QtWidgets.QAction(MainWindow)
        self.actionSaveParameters.setEnabled(False)
        self.actionSaveParameters.setObjectName("actionSaveParameters")
        self.actionCloseReduction = QtWidgets.QAction(MainWindow)
        self.actionCloseReduction.setEnabled(False)
        self.actionCloseReduction.setObjectName("actionCloseReduction")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionResetAllParameters = QtWidgets.QAction(MainWindow)
        self.actionResetAllParameters.setEnabled(False)
        self.actionResetAllParameters.setObjectName("actionResetAllParameters")
        self.actionSaveInputManifest = QtWidgets.QAction(MainWindow)
        self.actionSaveInputManifest.setEnabled(False)
        self.actionSaveInputManifest.setObjectName("actionSaveInputManifest")
        self.actionSaveOutputManifest = QtWidgets.QAction(MainWindow)
        self.actionSaveOutputManifest.setEnabled(False)
        self.actionSaveOutputManifest.setObjectName("actionSaveOutputManifest")
        self.actionSetOutputDirectory = QtWidgets.QAction(MainWindow)
        self.actionSetOutputDirectory.setEnabled(False)
        self.actionSetOutputDirectory.setObjectName("actionSetOutputDirectory")
        self.actionUpdateDisplays = QtWidgets.QAction(MainWindow)
        self.actionUpdateDisplays.setCheckable(True)
        self.actionUpdateDisplays.setChecked(True)
        self.actionUpdateDisplays.setObjectName("actionUpdateDisplays")
        self.actionDisplayIntermediate = QtWidgets.QAction(MainWindow)
        self.actionDisplayIntermediate.setCheckable(True)
        self.actionDisplayIntermediate.setChecked(True)
        self.actionDisplayIntermediate.setObjectName("actionDisplayIntermediate")
        self.actionLoadConfiguration = QtWidgets.QAction(MainWindow)
        self.actionLoadConfiguration.setObjectName("actionLoadConfiguration")
        self.actionSaveConfiguration = QtWidgets.QAction(MainWindow)
        self.actionSaveConfiguration.setObjectName("actionSaveConfiguration")
        self.actionResetConfiguration = QtWidgets.QAction(MainWindow)
        self.actionResetConfiguration.setObjectName("actionResetConfiguration")
        self.actionDisplayConfiguration = QtWidgets.QAction(MainWindow)
        self.actionDisplayConfiguration.setObjectName("actionDisplayConfiguration")
        self.menuFile.addAction(self.actionOpenNewReduction)
        self.menuFile.addAction(self.actionCloseReduction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAddFiles)
        self.menuFile.addAction(self.actionRemoveFiles)
        self.menuFile.addAction(self.actionSetOutputDirectory)
        self.menuFile.addAction(self.actionSaveInputManifest)
        self.menuFile.addAction(self.actionSaveOutputManifest)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuParameters.addAction(self.actionDisplayAllParameters)
        self.menuParameters.addAction(self.actionLoadParameters)
        self.menuParameters.addAction(self.actionSaveParameters)
        self.menuParameters.addAction(self.actionResetAllParameters)
        self.menuDisplay.addAction(self.actionUpdateDisplays)
        self.menuDisplay.addAction(self.actionDisplayIntermediate)
        self.menuSettings.addAction(self.actionLoadConfiguration)
        self.menuSettings.addAction(self.actionDisplayConfiguration)
        self.menuSettings.addAction(self.actionSaveConfiguration)
        self.menuSettings.addAction(self.actionResetConfiguration)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuParameters.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.dataTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Redux"))
        self.pipelineVersionLabel.setText(_translate("MainWindow", "Redux v2"))
        self.fileSummaryTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>"))
        self.stepButton.setText(_translate("MainWindow", "Step"))
        self.undoButton.setText(_translate("MainWindow", "Undo"))
        self.reduceButton.setText(_translate("MainWindow", "Reduce"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.label.setText(_translate("MainWindow", "Step through:"))
        self.dataTabWidget.setTabText(self.dataTabWidget.indexOf(self.fileInfoTab), _translate("MainWindow", "File Information"))
        self.logTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Menlo\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:20px; margin-bottom:20px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">==   Redux ready.   ==</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:36px; margin-right:36px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icons/redux_large.png\" width=\"480\" height=\"480\" /></p></body></html>"))
        self.dataTabWidget.setTabText(self.dataTabWidget.indexOf(self.logTab), _translate("MainWindow", "Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuParameters.setTitle(_translate("MainWindow", "Parameters"))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionOpenNewReduction.setText(_translate("MainWindow", "Open New Reduction"))
        self.actionAddFiles.setText(_translate("MainWindow", "Add Files"))
        self.actionRemoveFiles.setText(_translate("MainWindow", "Remove Files"))
        self.actionDisplayAllParameters.setText(_translate("MainWindow", "Display All Parameters"))
        self.actionLoadParameters.setText(_translate("MainWindow", "Load Parameters"))
        self.actionSaveParameters.setText(_translate("MainWindow", "Save Parameters"))
        self.actionCloseReduction.setText(_translate("MainWindow", "Close Reduction"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionResetAllParameters.setText(_translate("MainWindow", "Reset All Parameters"))
        self.actionSaveInputManifest.setText(_translate("MainWindow", "Save Input Manifest"))
        self.actionSaveOutputManifest.setText(_translate("MainWindow", "Save Output Manifest"))
        self.actionSetOutputDirectory.setText(_translate("MainWindow", "Set Output Directory"))
        self.actionUpdateDisplays.setText(_translate("MainWindow", "Update Displays"))
        self.actionDisplayIntermediate.setText(_translate("MainWindow", "Display Intermediate Steps"))
        self.actionLoadConfiguration.setText(_translate("MainWindow", "Load Configuration"))
        self.actionSaveConfiguration.setText(_translate("MainWindow", "Save Configuration"))
        self.actionResetConfiguration.setText(_translate("MainWindow", "Reset Configuration"))
        self.actionDisplayConfiguration.setText(_translate("MainWindow", "Edit Configuration"))

from . import redux_rc
from . import tango_rc
