# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qad_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(622, 1211)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 600, 1190))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imexamButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.imexamButton.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Tango/32x32/applications-accessories.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imexamButton.setIcon(icon)
        self.imexamButton.setIconSize(QtCore.QSize(32, 32))
        self.imexamButton.setObjectName("imexamButton")
        self.horizontalLayout.addWidget(self.imexamButton)
        self.headerButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Tango/32x32/edit-find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.headerButton.setIcon(icon1)
        self.headerButton.setIconSize(QtCore.QSize(32, 32))
        self.headerButton.setObjectName("headerButton")
        self.horizontalLayout.addWidget(self.headerButton)
        self.saveButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Tango/32x32/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon2)
        self.saveButton.setIconSize(QtCore.QSize(32, 32))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.status = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status.setText("")
        self.status.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.status.setObjectName("status")
        self.horizontalLayout_4.addWidget(self.status)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.disableDS9Box = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disableDS9Box.sizePolicy().hasHeightForWidth())
        self.disableDS9Box.setSizePolicy(sizePolicy)
        self.disableDS9Box.setText("")
        self.disableDS9Box.setObjectName("disableDS9Box")
        self.horizontalLayout_6.addWidget(self.disableDS9Box)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.disableOverplotsBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.disableOverplotsBox.setText("")
        self.disableOverplotsBox.setObjectName("disableOverplotsBox")
        self.horizontalLayout_6.addWidget(self.disableOverplotsBox)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 2, 1, 1)
        self.tileBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.tileBox.setText("")
        self.tileBox.setObjectName("tileBox")
        self.gridLayout.addWidget(self.tileBox, 8, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.lockSliceBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.lockSliceBox.setObjectName("lockSliceBox")
        self.lockSliceBox.addItem("")
        self.lockSliceBox.addItem("")
        self.lockSliceBox.addItem("")
        self.gridLayout.addWidget(self.lockSliceBox, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.colorMapBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.colorMapBox.setObjectName("colorMapBox")
        self.gridLayout.addWidget(self.colorMapBox, 6, 2, 1, 1)
        self.extensionBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.extensionBox.setEditable(True)
        self.extensionBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.extensionBox.setObjectName("extensionBox")
        self.extensionBox.addItem("")
        self.extensionBox.addItem("")
        self.extensionBox.addItem("")
        self.extensionBox.addItem("")
        self.extensionBox.addItem("")
        self.gridLayout.addWidget(self.extensionBox, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.zoomBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.zoomBox.setText("")
        self.zoomBox.setObjectName("zoomBox")
        self.gridLayout.addWidget(self.zoomBox, 7, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.scaleBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.scaleBox.setObjectName("scaleBox")
        self.scaleBox.addItem("")
        self.scaleBox.addItem("")
        self.scaleBox.addItem("")
        self.scaleBox.addItem("")
        self.gridLayout.addWidget(self.scaleBox, 5, 2, 1, 1)
        self.lockImageBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.lockImageBox.setObjectName("lockImageBox")
        self.lockImageBox.addItem("")
        self.lockImageBox.addItem("")
        self.lockImageBox.addItem("")
        self.gridLayout.addWidget(self.lockImageBox, 3, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 9, 0, 1, 1)
        self.snRangeBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.snRangeBox.setObjectName("snRangeBox")
        self.gridLayout.addWidget(self.snRangeBox, 9, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resetDispButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.resetDispButton.setObjectName("resetDispButton")
        self.horizontalLayout_3.addWidget(self.resetDispButton)
        self.restoreDispButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.restoreDispButton.setObjectName("restoreDispButton")
        self.horizontalLayout_3.addWidget(self.restoreDispButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bgwidBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bgwidBox.setObjectName("bgwidBox")
        self.gridLayout_2.addWidget(self.bgwidBox, 6, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 6, 0, 1, 1)
        self.bgrinBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bgrinBox.setObjectName("bgrinBox")
        self.gridLayout_2.addWidget(self.bgrinBox, 5, 1, 1, 1)
        self.apradUnitsBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.apradUnitsBox.setObjectName("apradUnitsBox")
        self.apradUnitsBox.addItem("")
        self.apradUnitsBox.addItem("")
        self.gridLayout_2.addWidget(self.apradUnitsBox, 4, 2, 1, 1)
        self.apradBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.apradBox.setObjectName("apradBox")
        self.gridLayout_2.addWidget(self.apradBox, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.fwhmUnitsBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.fwhmUnitsBox.setObjectName("fwhmUnitsBox")
        self.fwhmUnitsBox.addItem("")
        self.fwhmUnitsBox.addItem("")
        self.gridLayout_2.addWidget(self.fwhmUnitsBox, 3, 2, 1, 1)
        self.windowSizeBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.windowSizeBox.setObjectName("windowSizeBox")
        self.gridLayout_2.addWidget(self.windowSizeBox, 2, 1, 1, 1)
        self.modelTypeBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.modelTypeBox.setObjectName("modelTypeBox")
        self.modelTypeBox.addItem("")
        self.modelTypeBox.addItem("")
        self.gridLayout_2.addWidget(self.modelTypeBox, 1, 1, 1, 1)
        self.fwhmBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fwhmBox.setObjectName("fwhmBox")
        self.gridLayout_2.addWidget(self.fwhmBox, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.radialPlotBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.radialPlotBox.setText("")
        self.radialPlotBox.setObjectName("radialPlotBox")
        self.gridLayout_2.addWidget(self.radialPlotBox, 0, 1, 1, 1)
        self.windowUnitsBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.windowUnitsBox.setObjectName("windowUnitsBox")
        self.windowUnitsBox.addItem("")
        self.windowUnitsBox.addItem("")
        self.gridLayout_2.addWidget(self.windowUnitsBox, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resetPhotButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.resetPhotButton.setObjectName("resetPhotButton")
        self.horizontalLayout_2.addWidget(self.resetPhotButton)
        self.restorePhotButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.restorePhotButton.setObjectName("restorePhotButton")
        self.horizontalLayout_2.addWidget(self.restorePhotButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 2, 0, 1, 1)
        self.shareAxesBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.shareAxesBox.setObjectName("shareAxesBox")
        self.shareAxesBox.addItem("")
        self.shareAxesBox.addItem("")
        self.shareAxesBox.addItem("")
        self.shareAxesBox.addItem("")
        self.gridLayout_3.addWidget(self.shareAxesBox, 3, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 7, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 3, 0, 1, 1)
        self.plotWindowUnitsBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.plotWindowUnitsBox.setObjectName("plotWindowUnitsBox")
        self.plotWindowUnitsBox.addItem("")
        self.plotWindowUnitsBox.addItem("")
        self.gridLayout_3.addWidget(self.plotWindowUnitsBox, 1, 3, 1, 1)
        self.separatePlotsBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.separatePlotsBox.setText("")
        self.separatePlotsBox.setObjectName("separatePlotsBox")
        self.gridLayout_3.addWidget(self.separatePlotsBox, 4, 2, 1, 1)
        self.plotWindowSizeBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plotWindowSizeBox.setObjectName("plotWindowSizeBox")
        self.gridLayout_3.addWidget(self.plotWindowSizeBox, 1, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 4, 0, 1, 1)
        self.histBinBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.histBinBox.setObjectName("histBinBox")
        self.gridLayout_3.addWidget(self.histBinBox, 6, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 6, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 10, 0, 1, 1)
        self.histLimitsBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.histLimitsBox.setObjectName("histLimitsBox")
        self.gridLayout_3.addWidget(self.histLimitsBox, 7, 2, 1, 1)
        self.p2pReferenceBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.p2pReferenceBox.setObjectName("p2pReferenceBox")
        self.gridLayout_3.addWidget(self.p2pReferenceBox, 10, 2, 1, 1)
        self.plotColorBox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plotColorBox.setObjectName("plotColorBox")
        self.gridLayout_3.addWidget(self.plotColorBox, 2, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 5, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 9, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 8, 0, 1, 1)
        self.summaryStatBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.summaryStatBox.setObjectName("summaryStatBox")
        self.summaryStatBox.addItem("")
        self.summaryStatBox.addItem("")
        self.summaryStatBox.addItem("")
        self.summaryStatBox.addItem("")
        self.gridLayout_3.addWidget(self.summaryStatBox, 8, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.resetPlotButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.resetPlotButton.setObjectName("resetPlotButton")
        self.horizontalLayout_5.addWidget(self.resetPlotButton)
        self.restorePlotButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.restorePlotButton.setObjectName("restorePlotButton")
        self.horizontalLayout_5.addWidget(self.restorePlotButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_19.setText(_translate("Form", "QAD Tools"))
        self.imexamButton.setText(_translate("Form", "ImExam"))
        self.headerButton.setText(_translate("Form", "Header View"))
        self.saveButton.setText(_translate("Form", "Save Current Settings"))
        self.label_21.setText(_translate("Form", "Status:"))
        self.label_17.setText(_translate("Form", "Display Settings"))
        self.disableDS9Box.setToolTip(_translate("Form", "Set to disable DS9 display."))
        self.label_20.setText(_translate("Form", "Disable Overplots"))
        self.disableOverplotsBox.setToolTip(_translate("Form", "Set to disable automated overplots in DS9."))
        self.tileBox.setToolTip(_translate("Form", "Set to tile all loaded images in the DS9 window."))
        self.label_5.setText(_translate("Form", "Tile images"))
        self.label_6.setText(_translate("Form", "Scale"))
        self.label_3.setText(_translate("Form", "Lock slice to"))
        self.label_16.setText(_translate("Form", "Disable DS9"))
        self.label_7.setText(_translate("Form", "Extension to display"))
        self.lockSliceBox.setToolTip(_translate("Form", "If set to WCS, cube slices are locked to calibrated coordinates."))
        self.lockSliceBox.setItemText(0, _translate("Form", "WCS"))
        self.lockSliceBox.setItemText(1, _translate("Form", "Image"))
        self.lockSliceBox.setItemText(2, _translate("Form", "None"))
        self.label_2.setText(_translate("Form", "Color map"))
        self.colorMapBox.setToolTip(_translate("Form", "If none, colormap will not be updated on load."))
        self.extensionBox.setToolTip(_translate("Form", "Select extension display strategy, or edit to specify an extension number or name."))
        self.extensionBox.setCurrentText(_translate("Form", "First"))
        self.extensionBox.setItemText(0, _translate("Form", "First"))
        self.extensionBox.setItemText(1, _translate("Form", "All (in separate frames)"))
        self.extensionBox.setItemText(2, _translate("Form", "All (in a cube)"))
        self.extensionBox.setItemText(3, _translate("Form", "S/N"))
        self.extensionBox.setItemText(4, _translate("Form", "EXTNUM (edit to select a specific extension)"))
        self.label_4.setText(_translate("Form", "Zoom to fit"))
        self.label.setText(_translate("Form", "Lock frames to"))
        self.zoomBox.setToolTip(_translate("Form", "Set to zoom to fit the last loaded frame."))
        self.scaleBox.setToolTip(_translate("Form", "If none, scale will not be updated on load."))
        self.scaleBox.setItemText(0, _translate("Form", "ZScale"))
        self.scaleBox.setItemText(1, _translate("Form", "MinMax"))
        self.scaleBox.setItemText(2, _translate("Form", "ZMax"))
        self.scaleBox.setItemText(3, _translate("Form", "none"))
        self.lockImageBox.setToolTip(_translate("Form", "If set to WCS, frames and crosshair will be locked in sky coordinates."))
        self.lockImageBox.setCurrentText(_translate("Form", "WCS"))
        self.lockImageBox.setItemText(0, _translate("Form", "WCS"))
        self.lockImageBox.setItemText(1, _translate("Form", "Image"))
        self.lockImageBox.setItemText(2, _translate("Form", "None"))
        self.label_29.setText(_translate("Form", "S/N range"))
        self.snRangeBox.setToolTip(_translate("Form", "Set range for S/N image as min,max if desired."))
        self.resetDispButton.setToolTip(_translate("Form", "Reset display settings to last saved values."))
        self.resetDispButton.setText(_translate("Form", "Reset Display Settings"))
        self.restoreDispButton.setToolTip(_translate("Form", "Restore display settings to default values."))
        self.restoreDispButton.setText(_translate("Form", "Restore Default Display Settings"))
        self.label_18.setText(_translate("Form", "Photometry Settings"))
        self.bgwidBox.setToolTip(_translate("Form", "Width of background annulus."))
        self.label_15.setText(_translate("Form", "Background width"))
        self.bgrinBox.setToolTip(_translate("Form", "Starting radius of background annulus. Set to \'none\' to ignore background."))
        self.apradUnitsBox.setToolTip(_translate("Form", "Aperture radius and width units."))
        self.apradUnitsBox.setItemText(0, _translate("Form", "arcsec"))
        self.apradUnitsBox.setItemText(1, _translate("Form", "pixels"))
        self.apradBox.setToolTip(_translate("Form", "Radius of circular aperture, for summing flux."))
        self.label_8.setText(_translate("Form", "Background inner radius"))
        self.label_13.setText(_translate("Form", "Aperture radius"))
        self.fwhmUnitsBox.setToolTip(_translate("Form", "FWHM units."))
        self.fwhmUnitsBox.setItemText(0, _translate("Form", "arcsec"))
        self.fwhmUnitsBox.setItemText(1, _translate("Form", "pixels"))
        self.windowSizeBox.setToolTip(_translate("Form", "Region to consider for fitting."))
        self.modelTypeBox.setToolTip(_translate("Form", "Profile type to fit."))
        self.modelTypeBox.setItemText(0, _translate("Form", "Moffat"))
        self.modelTypeBox.setItemText(1, _translate("Form", "Gaussian"))
        self.fwhmBox.setToolTip(_translate("Form", "Expected source width, as FWHM."))
        self.label_9.setText(_translate("Form", "Window size"))
        self.label_10.setText(_translate("Form", "Model type"))
        self.label_11.setText(_translate("Form", "Starting FWHM"))
        self.label_14.setText(_translate("Form", "Show radial plots "))
        self.radialPlotBox.setToolTip(_translate("Form", "Display radial profiles for fit sources."))
        self.windowUnitsBox.setToolTip(_translate("Form", "Units for window size."))
        self.windowUnitsBox.setItemText(0, _translate("Form", "pixels"))
        self.windowUnitsBox.setItemText(1, _translate("Form", "arcsec"))
        self.resetPhotButton.setToolTip(_translate("Form", "Reset photometry settings to last saved values."))
        self.resetPhotButton.setText(_translate("Form", "Reset Photometry Settings"))
        self.restorePhotButton.setToolTip(_translate("Form", "Restore photometry settings to default values."))
        self.restorePhotButton.setText(_translate("Form", "Restore Default Photometry Settings"))
        self.label_22.setText(_translate("Form", "Plot Settings"))
        self.label_24.setText(_translate("Form", "Plot color cycle"))
        self.shareAxesBox.setToolTip(_translate("Form", "Specify axes to share, between separate plots."))
        self.shareAxesBox.setItemText(0, _translate("Form", "none"))
        self.shareAxesBox.setItemText(1, _translate("Form", "x"))
        self.shareAxesBox.setItemText(2, _translate("Form", "y"))
        self.shareAxesBox.setItemText(3, _translate("Form", "both"))
        self.label_27.setText(_translate("Form", "Histogram range"))
        self.label_25.setText(_translate("Form", "Share axes"))
        self.plotWindowUnitsBox.setToolTip(_translate("Form", "Units for window size."))
        self.plotWindowUnitsBox.setItemText(0, _translate("Form", "pixels"))
        self.plotWindowUnitsBox.setItemText(1, _translate("Form", "arcsec"))
        self.separatePlotsBox.setToolTip(_translate("Form", "If not set, new plots will be added to existing axes."))
        self.plotWindowSizeBox.setToolTip(_translate("Form", "Analysis window around cursor."))
        self.label_23.setText(_translate("Form", "Analysis window size"))
        self.label_12.setText(_translate("Form", "Separate plots"))
        self.histBinBox.setToolTip(_translate("Form", "Binning strategy for histograms."))
        self.label_26.setText(_translate("Form", "Histogram binning"))
        self.label_28.setText(_translate("Form", "P2P reference"))
        self.histLimitsBox.setToolTip(_translate("Form", "Set range as min,max if desired."))
        self.p2pReferenceBox.setToolTip(_translate("Form", "Reference frame number for pixel-to-pixel comparisons."))
        self.plotColorBox.setToolTip(_translate("Form", "Set to any valid matplotlib colormap name."))
        self.label_31.setText(_translate("Form", "Histogram (\'s\'):"))
        self.label_32.setText(_translate("Form", "Pixel-to-pixel (\'p\'):"))
        self.label_30.setText(_translate("Form", "General:"))
        self.label_33.setText(_translate("Form", "Summary statistic"))
        self.summaryStatBox.setItemText(0, _translate("Form", "mean"))
        self.summaryStatBox.setItemText(1, _translate("Form", "median"))
        self.summaryStatBox.setItemText(2, _translate("Form", "clipped mean"))
        self.summaryStatBox.setItemText(3, _translate("Form", "clipped median"))
        self.resetPlotButton.setToolTip(_translate("Form", "Reset plot settings to last saved value."))
        self.resetPlotButton.setText(_translate("Form", "Reset Plot Settings"))
        self.restorePlotButton.setToolTip(_translate("Form", "Restore plot settings values to default values."))
        self.restorePlotButton.setText(_translate("Form", "Restore Default Plot Settings"))

from . import tango_rc
